In [1]:
import numpy as np

## Construct a list and a numpy array with numbers 1 to 1,000,000 , compare the times it takes to square all the numbers 10 times

Before first iteration you have 0,1,2,3  
before second iteration you have 0,1,4,9  
before third you have 0,1,16,81  

In [34]:
arr = np.arange(1000000)
lst = list(range(1000000))

In [35]:
%time for _ in range(10): arr = arr ** 2

Wall time: 19.9 ms


In [41]:
arr[5]

689565697

In [36]:
%time for _ in range(10): lst = [x ** 2 for x in lst]

Wall time: 1min 6s


### Why was one faster than the other? What are other reasons we might use one over the other?

### Look back at your np array, are the answers what you expected?

## Construct a 5x5 array with numbers 1 to 25 in order

$$
\begin{array}{cc} 
1  & 2 & 3 & 4 & 5\\
6 & 7 & 8 & 9 & 10\\
11 & 12 & 13 & 14 & 15\\
16 & 17 & 18 & 19 & 20\\
21 & 22 & 23 & 24 & 25
\end{array}
$$ 

In [13]:
np.arange(25).reshape(5,5) + 1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Construct this pattern as efficiently as you can

$$
\begin{array}{cc} 
1 & 1 & 1 & 1 & 1\\
1 & 0 & 0 & 0 & 1\\
1 & 0 & 9 & 0 & 1\\
1 & 0 & 0 & 0 & 1\\
1 & 1 & 1 & 1 & 1
\end{array}
$$ 

In [3]:
a = np.ones((5,5))
b = np.zeros((3,3))
b[1,1] = 9
a[1:-1,1:-1] = b
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Create an array of size 10 by 10, filled by random floats, of range 40 to 50

In [27]:
a = 10*np.random.random_sample((10,10)) + 40

In [15]:
b = a.copy()

### Replace 10 of these values randomly with a suitable value to show it's missing

In [28]:
a[np.random.randint(10, size=10), np.random.randint(10, size=10)] = np.nan

In [17]:
b = b.ravel()

In [18]:
x = np.arange(100)
np.random.shuffle(x)
b[x[:10]] = np.nan
b.reshape(10,10)

array([[46.39111198, 49.34731225, 44.89170138, 42.15064395, 44.55382197,
        44.16137781, 47.27182763, 45.34534012,         nan, 46.03609431],
       [49.91636407, 41.51635719, 44.02598472, 41.61980998, 45.43059031,
        47.40239101, 42.02964448, 44.42088851, 45.50563992, 47.05133408],
       [        nan, 47.13320565, 48.25327997, 44.7509674 , 40.01443741,
        48.98581005,         nan, 48.5060458 ,         nan, 49.0709388 ],
       [42.39524354, 42.63858369, 42.90860544,         nan, 48.9748844 ,
        43.58848051, 44.01730645, 48.45079548, 45.8702253 ,         nan],
       [45.93943565, 44.08171306, 44.04634405, 49.2743384 , 47.70839164,
        48.18882159, 47.1217316 , 44.98650079, 48.81176923, 43.15175878],
       [43.02135197, 41.94596831,         nan, 45.03762496, 41.66769417,
        45.31349635, 49.21747894, 43.75984672, 42.00677179, 41.26935581],
       [47.35328368, 46.37361862, 46.14385   , 49.93553264,         nan,
        48.64940832,         nan, 43.77892543

### Extract only the numbers that aren't nans (as a single row)

In [29]:
a[~np.isnan(a)]

array([42.78215055, 41.31054313, 41.2983776 , 47.30427763, 49.89498341,
       45.29977891, 45.30304805, 47.69026015, 48.8358678 , 42.4604808 ,
       40.0150388 , 49.68439351, 43.51216658, 49.79584198, 43.52780459,
       45.08832655, 40.68359019, 46.36093576, 49.42399374, 42.36190312,
       42.28383419, 40.61572479, 42.40873218, 46.60291599, 42.19216971,
       40.62684216, 49.89280772, 44.74647217, 41.22760108, 47.70494511,
       48.91786574, 40.24304885, 49.53383077, 43.12489807, 46.37077152,
       44.28102536, 47.65171956, 44.25145186, 45.65169619, 47.1119958 ,
       41.44746892, 49.69933537, 46.20217706, 45.92693065, 49.09447754,
       44.72911152, 43.09015883, 43.8472887 , 45.83286241, 49.97289891,
       49.23659096, 49.89118125, 49.55085974, 42.33216431, 47.02735981,
       46.91952414, 49.07775491, 41.79820143, 44.05498933, 43.29594093,
       43.67964868, 48.85461261, 43.25380402, 40.99714362, 42.9320541 ,
       49.04054853, 40.03482916, 47.93120341, 47.1675708 , 42.73

### Fill the missing values with the mean of the rest of the matrix

In [45]:
a = a.ravel()

In [46]:
a[np.isnan(a)] = np.mean(b[~np.isnan(a)])

In [47]:
a = a.reshape(10,10)

### Rank all the numbers according to order

example: 43, 49, 47 would become 0, 2, 1

In [48]:
a.ravel().argsort().argsort().reshape(10,10)

array([[28, 12, 11, 77, 98, 61, 52, 62, 79, 83],
       [25,  0, 93, 36, 95, 38, 50,  6, 69, 90],
       [54, 22, 20,  4, 24, 72, 19,  5, 97, 48],
       [10, 80, 85,  2, 91, 60, 32, 53, 70, 44],
       [78, 57, 43, 64, 75, 13, 94, 59, 68, 66],
       [88, 47, 31, 41, 65, 99, 89, 55, 96, 92],
       [21, 74, 73, 87, 17, 42, 35, 56, 39, 84],
       [34,  8, 30, 86,  1, 81, 76, 27, 51, 40],
       [71,  3, 26, 23, 49, 82, 33, 63, 15, 18],
       [46, 58, 16, 67,  9, 14,  7, 37, 29, 45]], dtype=int64)

In [49]:
a

array([[42.78215055, 41.31054313, 41.2983776 , 47.30427763, 49.89498341,
        45.29977891, 45.28943562, 45.30304805, 47.69026015, 48.8358678 ],
       [42.4604808 , 40.0150388 , 49.68439351, 43.51216658, 49.79584198,
        43.52780459, 45.08832655, 40.68359019, 46.36093576, 49.42399374],
       [45.28943562, 42.36190312, 42.28383419, 40.61572479, 42.40873218,
        46.60291599, 42.19216971, 40.62684216, 49.89280772, 44.74647217],
       [41.22760108, 47.70494511, 48.91786574, 40.24304885, 49.53383077,
        45.28943562, 43.12489807, 45.28943562, 46.37077152, 44.28102536],
       [47.65171956, 45.28943562, 44.25145186, 45.65169619, 47.1119958 ,
        41.44746892, 49.69933537, 45.28943562, 46.20217706, 45.92693065],
       [49.09447754, 44.72911152, 43.09015883, 43.8472887 , 45.83286241,
        49.97289891, 49.23659096, 45.28943562, 49.89118125, 49.55085974],
       [42.33216431, 47.02735981, 46.91952414, 49.07775491, 41.79820143,
        44.05498933, 43.29594093, 45.28943562