In [1]:
import numpy as np

## Construct a list and a numpy array with numbers 1 to 1,000,000 , compare the times it takes to square all the numbers 10 times

Before first iteration you have 0,1,2,3  
before second iteration you have 0,1,4,9  
before third you have 0,1,16,81  

In [2]:
arr = np.arange(1000000)
lst = list(range(1000000))

In [3]:
lst[1]

1

In [4]:
%time for _ in range(10): arr = arr ** 2

Wall time: 24.9 ms


In [5]:
arr[5]

689565697

In [6]:
%time for _ in range(10): lst = [x ** 2 for x in lst]

Wall time: 1min 19s


### Why was one faster than the other? What are other reasons we might use one over the other?

dtype('int32')

In [8]:
x = 100

In [9]:
x = x**2
x

10000

### Look back at your np array, are the answers what you expected?

In [10]:
arr[0:5]

array([          0,           1,           0, -1876701183,           0],
      dtype=int32)

## Create a numpy array with the single value of 8. Raise it to the 21st power. Do you get an accurate value?

In [11]:
x = np.array([8])

In [12]:
x**21

array([0], dtype=int32)

### What change can you make to the numpy array/in making a new array to get an accurate answer for 8 to the power 21

In [13]:
np.array([8], dtype = 'uint64') ** 21

array([9223372036854775808], dtype=uint64)

In [14]:
8**21

9223372036854775808

## Construct a 5x5 array with numbers 1 to 25 in order

$$
\begin{array}{cc} 
1  & 2 & 3 & 4 & 5\\
6 & 7 & 8 & 9 & 10\\
11 & 12 & 13 & 14 & 15\\
16 & 17 & 18 & 19 & 20\\
21 & 22 & 23 & 24 & 25
\end{array}
$$ 

In [15]:
np.arange(25).reshape(5,5) + 1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Construct this pattern as efficiently as you can

$$
\begin{array}{cc} 
1 & 1 & 1 & 1 & 1\\
1 & 0 & 0 & 0 & 1\\
1 & 0 & 9 & 0 & 1\\
1 & 0 & 0 & 0 & 1\\
1 & 1 & 1 & 1 & 1
\end{array}
$$ 

In [16]:
a = np.ones((5,5))
b = np.zeros((3,3))
b[1,1] = 9
a[1:-1,1:-1] = b
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Create an array of size 10 by 10, filled by random floats, of range 40 to 50

In [17]:
a = 10*np.random.random_sample((10,10)) + 40

In [18]:
b = a.copy()

### Replace 10 of these values randomly with a suitable value to show it's missing

In [19]:
a[np.random.randint(10, size=10), np.random.randint(10, size=10)] = np.nan

In [20]:
a[[1,4,8,2,3],[6,8,3,5,6]]

array([45.97058543, 42.84485871, 49.76285748, 41.58545143, 41.65511383])

In [21]:
b = b.ravel()

In [22]:
x = np.arange(100)
np.random.shuffle(x)
b[x[:10]] = np.nan
b.reshape(10,10)

array([[44.13274579, 48.0506771 , 48.65759433, 49.17411366, 43.76690368,
        48.16059193,         nan,         nan, 45.5399368 , 48.25640301],
       [46.88815193, 41.2178183 ,         nan, 47.65383138, 42.30283512,
        40.88066646, 45.97058543, 41.25351301, 47.04274072, 43.00073214],
       [46.62808017, 45.50820244, 45.61519784, 43.87031224, 45.67786933,
        41.58545143,         nan, 43.27672507, 42.99209785, 40.38672976],
       [43.39683384, 45.63957517, 47.21084847, 47.44511774, 46.88168565,
        46.47943262, 41.65511383, 47.3560906 , 44.76901263, 42.98361153],
       [        nan, 46.92362057, 42.16571065, 47.86410942, 48.9706669 ,
        49.44876472, 46.45956174, 44.14097412, 42.84485871, 42.5920899 ],
       [40.25521985, 48.0756283 , 47.25351964, 42.61365373, 46.25667075,
        42.99220431, 41.08417718, 49.9335825 ,         nan, 44.90522538],
       [43.08727717, 46.57972811,         nan, 48.84506562,         nan,
        42.83648825, 43.64378076, 40.5881698 

### Extract only the numbers that aren't nans (as a single row)

In [23]:
a[~np.isnan(a)]

array([44.13274579, 48.0506771 , 48.65759433, 49.17411366, 43.76690368,
       48.16059193, 45.43853908, 45.5399368 , 48.25640301, 46.88815193,
       41.2178183 , 42.26343172, 47.65383138, 42.30283512, 40.88066646,
       45.97058543, 41.25351301, 47.04274072, 43.00073214, 46.62808017,
       45.50820244, 43.87031224, 45.67786933, 41.58545143, 47.57237749,
       43.27672507, 42.99209785, 40.38672976, 43.39683384, 45.63957517,
       47.21084847, 46.88168565, 46.47943262, 41.65511383, 47.3560906 ,
       44.76901263, 42.36960387, 46.92362057, 42.16571065, 47.86410942,
       48.9706669 , 46.45956174, 44.14097412, 42.84485871, 42.5920899 ,
       40.25521985, 48.0756283 , 47.25351964, 42.61365373, 46.25667075,
       42.99220431, 41.08417718, 49.9335825 , 49.11168736, 44.90522538,
       43.08727717, 46.57972811, 48.84506562, 47.20513523, 42.83648825,
       43.64378076, 40.5881698 , 45.85066835, 40.28147543, 47.21351353,
       43.4956701 , 42.41360211, 42.91296099, 49.31933577, 40.26

### Fill the missing values with the mean of the rest of the matrix

In [24]:
a = a.ravel()

In [25]:
a[np.isnan(a)] = np.mean(a[~np.isnan(a)])

In [26]:
a = a.reshape(10,10)

### Rank all the numbers according to order

example: 43, 49, 47 would become 0, 2, 1

In [27]:
a.ravel().argsort().argsort().reshape(10,10)

array([[38, 86, 91, 95, 35, 88, 51, 59, 61, 89],
       [73, 10, 16, 84, 17,  5, 65, 11, 75, 28],
       [71, 60, 55, 36, 63, 12, 83, 30, 26,  3],
       [31, 62, 78, 53, 72, 69, 13, 82, 46, 47],
       [19, 74, 15, 85, 93, 56, 68, 39, 24, 21],
       [ 0, 87, 80, 22, 67, 27,  9, 99, 94, 57],
       [29, 70, 54, 92, 77, 23, 34,  4, 64,  2],
       [79, 52, 33, 20, 25, 96,  1, 37, 76, 50],
       [41, 58, 40, 98, 18,  7, 81, 66, 42, 49],
       [48, 43,  6, 44, 97, 90, 14, 32, 45,  8]], dtype=int64)

In [28]:
a

array([[44.13274579, 48.0506771 , 48.65759433, 49.17411366, 43.76690368,
        48.16059193, 44.85582411, 45.43853908, 45.5399368 , 48.25640301],
       [46.88815193, 41.2178183 , 42.26343172, 47.65383138, 42.30283512,
        40.88066646, 45.97058543, 41.25351301, 47.04274072, 43.00073214],
       [46.62808017, 45.50820244, 44.85582411, 43.87031224, 45.67786933,
        41.58545143, 47.57237749, 43.27672507, 42.99209785, 40.38672976],
       [43.39683384, 45.63957517, 47.21084847, 44.85582411, 46.88168565,
        46.47943262, 41.65511383, 47.3560906 , 44.76901263, 44.85582411],
       [42.36960387, 46.92362057, 42.16571065, 47.86410942, 48.9706669 ,
        44.85582411, 46.45956174, 44.14097412, 42.84485871, 42.5920899 ],
       [40.25521985, 48.0756283 , 47.25351964, 42.61365373, 46.25667075,
        42.99220431, 41.08417718, 49.9335825 , 49.11168736, 44.90522538],
       [43.08727717, 46.57972811, 44.85582411, 48.84506562, 47.20513523,
        42.83648825, 43.64378076, 40.5881698 